### ISSUE TITLE
Change build command for CI

### ISSUE THREAD

**Issue by ink8bit** [ink8bit/ts-lib-template#7]
# Build command

https://github.com/ink8bit/ts-lib-template/blob/b87ae7e70742bfdb57b6137cff8f4ae70db98159/.github/workflows/nodejs.yml#L26

Need to change this to:

```yml
- run: npm run types:check
- run: npm run format:check
- run: npm run lint
- run: npm run test:ci
```
